import { readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { compileSvg, validatePackManifest } from "./compile-lib.mjs";

const root = path.resolve(import.meta.dirname, "..");
const packsRoot = path.join(import.meta.dirname, "packs");
const frontendOutput = path.join(
  root,
  "dnd_vtt_frontend",
  "src",
  "app",
  "core",
  "avatar",
  "custom-avatar-assets.generated.ts",
);
const backendOutput = path.join(
  root,
  "dnd_vtt_backend",
  "src",
  "common",
  "custom-avatar-manifest.generated.ts",
);

const entries = await readdir(packsRoot, { withFileTypes: true });
const compiledPacks = [];
const backendStyles = {};
for (const entry of entries
  .filter((item) => item.isDirectory())
  .sort((a, b) => a.name.localeCompare(b.name))) {
  const packRoot = path.join(packsRoot, entry.name);
  const manifest = validatePackManifest(
    JSON.parse(await readFile(path.join(packRoot, "catalog.json"), "utf8")),
    `${entry.name}/catalog.json`,
  );
  const assets = {};
  for (const category of manifest.categories) {
    assets[category.id] = {};
    for (const part of category.parts) {
      const source = await readFile(path.join(packRoot, part.file), "utf8");
      assets[category.id][part.id] = compileSvg(
        source,
        manifest,
        `${category.id}-${part.id}`,
      );
    }
  }
  if (manifest.enabled)
    compiledPacks.push({
      definition: {
        id: manifest.id,
        version: manifest.version,
        label: manifest.label,
        viewBox: manifest.viewBox,
        categories: manifest.categories.map((category) => ({
          id: category.id,
          label: category.label,
          minSelections: category.minSelections,
          maxSelections: category.maxSelections,
          noneWeight: category.noneWeight,
          parts: category.parts.map(({ file: _file, ...part }) => part),
        })),
        colors: manifest.colors,
      },
      assets,
    });
  if (manifest.enabled) {
    backendStyles[manifest.id] = {
      version: manifest.version,
      categories: Object.fromEntries(
        manifest.categories.map((category) => [
          category.id,
          {
            min: category.minSelections,
            max: category.maxSelections,
            parts: category.parts.map((part) => part.id),
            occupies: Object.fromEntries(
              category.parts
                .filter((part) => part.occupies?.length)
                .map((part) => [part.id, part.occupies]),
            ),
            conflicts: Object.fromEntries(
              category.parts
                .filter((part) => part.conflictsWith?.length)
                .map((part) => [part.id, part.conflictsWith]),
            ),
          },
        ]),
      ),
      colors: manifest.colors.map((color) => color.id),
    };
  }
}

await writeFile(
  frontendOutput,
  `// Generated by avatar-assets/compile.mjs. Do not edit by hand.\nexport const GENERATED_LAYERED_AVATAR_PACKS = ${JSON.stringify(compiledPacks, null, 2)} as const;\n`,
);
await writeFile(
  backendOutput,
  `// Generated by avatar-assets/compile.mjs. Do not edit by hand.\nexport const CUSTOM_AVATAR_STYLES = ${JSON.stringify(backendStyles, null, 2)} as const;\n`,
);
console.log(`Compiled ${compiledPacks.length} enabled custom avatar pack(s).`);
